version: '3'
services:
    api:
        build:
            context: .
            args:
                - MVNWARGS="-Dmaven.test.skip=true"
        image: xyzrlee/api
        ports:
            - 9999:8080/tcp
        environment:
            - JVMARGS=-Xmx512m
